In [ ]:
"""
Tensor rotations
"""

import torch

# 90 degree rotation of 3d tensor around the z axis

x = torch.tensor([
  [[1, 2, 3],
   [4, 5, 6],
   [7, 8, 9]],

  [[10, 11, 12],
   [13, 14, 15],
   [16, 17, 18]],

  [[19, 20, 21],
   [22, 23, 24],
   [25, 26, 27]]
])
print(x)
x = x.permute(0, 2, 1)
x = torch.flip(x, dims=[2])
print(x)

print("\n")

# 180 degree rotation of 2d tensor

x = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(x)
x = torch.flip(x, dims = (0, 1))
print(x)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])
tensor([[[ 7,  4,  1],
         [ 8,  5,  2],
         [ 9,  6,  3]],

        [[16, 13, 10],
         [17, 14, 11],
         [18, 15, 12]],

        [[25, 22, 19],
         [26, 23, 20],
         [27, 24, 21]]])


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])
