In [ ]:
"""
Tensor rotations
"""

import torch

# 90 degree rotation of 3d tensor around the z axis

x = torch.tensor([
  [[1, 2, 3],
   [4, 5, 6],
   [7, 8, 9]],

  [[10, 11, 12],
   [13, 14, 15],
   [16, 17, 18]],

  [[19, 20, 21],
   [22, 23, 24],
   [25, 26, 27]]
])
print(x)
x = x.permute(0, 2, 1)
x = torch.flip(x, dims=[2])
print(x)

print("\n")

# 180 degree rotation of 2d tensor

x = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(x)
x = torch.flip(x, dims = (0, 1))
print(x)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])
tensor([[[ 7,  4,  1],
         [ 8,  5,  2],
         [ 9,  6,  3]],

        [[16, 13, 10],
         [17, 14, 11],
         [18, 15, 12]],

        [[25, 22, 19],
         [26, 23, 20],
         [27, 24, 21]]])


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])


In [ ]:
"""
Tensor views and indexing
"""

import torch

# finding the largest value in each sliding window

x = torch.tensor([1, 3, 5, 3, 4, 8, -3, 4, 1, 6, 10, -2, 4, 7, 9, 2, 4, 8])

x = torch.amax(x.unfold(0, 3, 1), 1)
print(x)


# switching the diagonals on a 3x3 tensor

x = torch.rand(3, 3, 3)
print(x)

index = torch.tensor([
  [[2, 1, 0],
   [0, 1, 2],
   [2, 1, 0]],

  [[2, 1, 0],
   [0, 1, 2],
   [2, 1, 0]],

  [[2, 1, 0],
   [0, 1, 2],
   [2, 1, 0]]
])

x = torch.gather(x, 2, index)
print(x)

# circularly shift rows in a 2D tensor given a 1D tensor of shift amounts

x = torch.rand(4, 6)
print(x)

shifts = torch.tensor([1, 2, 3, 5])
base = torch.arrange(6)

# turn into horizontal and vertical tensors
shifts = shifts.unsqueeze(1)
base = base.unsqueeze(0)


indexes = (base - )



tensor([ 5,  5,  5,  8,  8,  8,  4,  6, 10, 10, 10,  7,  9,  9,  9,  8])
tensor([[[0.8737, 0.5528, 0.5770],
         [0.6185, 0.6116, 0.3101],
         [0.6372, 0.4567, 0.8060]],

        [[0.3298, 0.3033, 0.2653],
         [0.0106, 0.8557, 0.1313],
         [0.2518, 0.4584, 0.1092]],

        [[0.7634, 0.8028, 0.6114],
         [0.4391, 0.6004, 0.7546],
         [0.3674, 0.8913, 0.2813]]])
tensor([[[0.5770, 0.5528, 0.8737],
         [0.6185, 0.6116, 0.3101],
         [0.8060, 0.4567, 0.6372]],

        [[0.2653, 0.3033, 0.3298],
         [0.0106, 0.8557, 0.1313],
         [0.1092, 0.4584, 0.2518]],

        [[0.6114, 0.8028, 0.7634],
         [0.4391, 0.6004, 0.7546],
         [0.2813, 0.8913, 0.3674]]])
